sonar.organization=setchy
sonar.projectKey=setchy_meme-driven.dev

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src
sonar.sourceEncoding=UTF-8